language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed "

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-be-feed .
  - docker tag udagram-be-feed dgrafova/udagram-be-feed:latest
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push dgrafova/udagram-be-feed:latest
